"""Add stocks and stock_daily_data tables and set FKs

Revision ID: 2de26bce7d85
Revises: f2569f8660b5
Create Date: 2026-03-21 23:03:21.160237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de26bce7d85'
down_revision = 'f2569f8660b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ticker_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.Enum('KOSPI', 'KOSDAQ', name='markettype'), nullable=False),
    sa.PrimaryKeyConstraint('ticker_code')
    )
    # Populate missing stocks from existing holdings and orders
    op.execute("INSERT IGNORE INTO stocks (ticker_code, name, market_type) "
               "SELECT DISTINCT ticker_code, 'Unknown', 'KOSPI' FROM holdings")
    op.execute("INSERT IGNORE INTO stocks (ticker_code, name, market_type) "
               "SELECT DISTINCT ticker_code, 'Unknown', 'KOSPI' FROM orders")
    
    op.create_table('stock_daily_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_code', sa.String(length=10), nullable=False),
    sa.Column('stk_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.BigInteger(), nullable=True),
    sa.Column('high_price', sa.BigInteger(), nullable=True),
    sa.Column('low_price', sa.BigInteger(), nullable=True),
    sa.Column('close_price', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_code'], ['stocks.ticker_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'stocks', ['ticker_code'], ['ticker_code'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'stocks', ['ticker_code'], ['ticker_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('stock_daily_data')
    op.drop_table('stocks')
    # ### end Alembic commands ###
